const mongoose = require('mongoose');

//user 
//job description schema  :string
//resume schema :string
//self description schema :string

//ai
//matchscore number : number
//technical question  : [{question : "" ,intention: "" ,  answer : ""}]
//behavioural question : [{question : "" ,intention: "" ,  answer : ""}]
//skill gaps :[{skill :"" ,severity : "" }]
//prepration plan :[{day:numbr , focus:string , tasks:[string]}]
const technicalQuestionSchema = new mongoose.Schema({       //it will be generated by ai 
    question :{
        type : String,
        required : [true, 'Technical question is required']
    },
    intention : {
        type : String,
        required : [true, 'Intention for technical question is required']
    },
    answer : {
        type : String,
        required : [true, 'Answer for technical question is required']
    },
    _id : false                      //because id not required for question and answer subdocument
})


const behaviouralQuestionSchema = new mongoose.Schema({       //it will be generated by ai 
    question :{
        type : String,
        required : [true, 'Behavioural question is required']
    },
    intention : {
        type : String,
        required : [true, 'Intention for behavioural question is required']
    },
    answer : {
        type : String,
        required : [true, 'Answer for behavioural question is required']
    },
    _id : false                      //because id not required for question and answer subdocument
})

const skillGapSchema = new mongoose.Schema({
    skillGap : {
        type : String,
        required : [true, 'Skill gap is required']
    },
    severity : {
        type : String,
        enum :['low' ,'medium','high'],
        required : [true, 'Severity for skill gap is required']
    },
    _id : false
});

const preparationPlanSchema = new mongoose.Schema({
    day : {
        type : Number,
        required : [true, 'Day for preparation plan is required']
    },
    focus :{
        type : String,
        required : [true, 'Focus for preparation plan is required']
    },
    tasks : {
        type : [String],
        required : [true, 'Tasks for preparation plan is required']
    }
})

//finally the main interview report schema which will be stored in the database
const interviewReportSchema = new mongoose.Schema({
    jobDescription : {
        type : String,
        required : [true, 'Job description is required']
    },
    resume : {
        type : String,
    },
    selfDescription : {
        type : String,
    },
    matchScore : {
        type : Number,
        min : 0,
        max : 100
    },  
    technicalquestion : [technicalQuestionSchema],
    behaviouralQuestion : [behaviouralQuestionSchema],
    skillGaps : [skillGapSchema],
    preparationPlan : [preparationPlanSchema],
    user : {
        type : mongoose.Schema.Types.ObjectId,
        ref : 'User',
        required : true
    },
    title : {
        type : String,
        required : [true, 'Title for interview report is required']
    }
});

const InterviewReportModel = mongoose.model('InterviewReport',interviewReportSchema);
module.exports = InterviewReportModel;

